---
deployment:
  tasks:
    - export DEPLOYPATH=/home/justforr/transfertco.ca/public_html/
    - /bin/cp -R sender.html $DEPLOYPATH
    - /bin/cp -R CastVideos.js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH