deployment:
  tasks:
    - export DEPLOYPATH=/home/justforr/repositories/cls411-chromecast/
    - /bin/cp -R receiver.css $DEPLOYPATH
    - /bin/cp -R receiver.html $DEPLOYPATH
    - /bin/cp -R sender.html $DEPLOYPATH
    - /bin/cp -R CastVideos.js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH